---
title: "PL Period Report"
author: "Andrew Noecker"
date: '2022-07-16'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gt)
library(DT)
library(rvest)
library(tidyverse)

source("R/Period Reports/pitcher_diff.r")
source("R/Period Reports/batter_diff.r")
```


```{r Define Termi Hitters}
# Termi hitters
termi_hitters <- c("Daulton Varsho",
                   "Freddie Freeman",
                   "Trea Turner",
                   "Wilmer Flores",
                   "Jeremy Pena", 
                   "Luke Voit",
                   "Nico Hoerner",
                   "Byron Buxton",
                   "Nick Castellanos",
                   "Randy Arozarena",
                   "Christian Yelich",
                   "Josh Donaldson", 
                   "Hunter Renfroe",
                   "Leody Taveras",
                   "Christopher Morel",
                   "Ty France",
                   "Joey Votto",
                   "Tommy Pham",
                   "Seiya Suzuki")
```



# Hitter Reports

## 15 Days 

#### Termi Hitters

```{r}
batters15 <- fg_batter_stats(Sys.Date() - 15, Sys.Date(), qual = 5) 

termis15 <- batters15 %>%
  filter(Name %in% termi_hitters) %>% 
  select(1:9, 24:29, 10:23, 30:31)

# termis15 %>% 
#   gt() %>% 
#   data_color(
#     columns = `Barrel%`,
#     colors = scales::col_numeric(
#       palette = c("red", "orange", "green", "blue"),
#       domain = c(0, 35)
#     )
#   ) %>%
#   data_color(
#     columns = `HardHit%`,
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(0, 70)
#     )
#   ) %>%
#   tab_header(
#     title = "Termi Hitters 15 Day Report",
#     subtitle = "Arranged in descending barrel%"
#   )

datatable(termis15, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```

#### League Wide

```{r}
datatable(batters15, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```

## 30 Days 


#### Termi Hitters 

```{r}
batters30 <- fg_batter_stats(Sys.Date() - 30, Sys.Date(), qual = 5) 

termis30 <- batters30 %>%
  filter(Name %in% termi_hitters)%>% 
  select(1:9, 24:29, 10:23, 30:31)

datatable(termis30, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))
```

#### League Wide

```{r}
datatable(batters30, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```


## 45 Days 

#### Termi Hitters 

```{r}
batters45 <- fg_batter_stats(Sys.Date() - 45, Sys.Date(), qual = 5) 

termis45 <- batters45 %>%
  filter(Name %in% termi_hitters)%>% 
  select(1:9, 24:29, 10:23, 30:31)

datatable(termis45, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```


#### League Wide

```{r}
datatable(batters45, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```












