---
title: "PL Report"
author: "Andrew Noecker"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gt)
library(DT)
library(rvest)
library(tidyverse)

source("R/Period-Reports/pitcher_diff.r")
source("R/Period-Reports/batter_diff.r")
```


```{r Define Termi Roster}
# Termi hitters
termi_hitters <- c("Daulton Varsho",
                   "Freddie Freeman",
                   "Trea Turner",
                   "Wilmer Flores",
                   "Jeremy Pena", 
                   "Luke Voit",
                   "Nico Hoerner",
                   "Byron Buxton",
                   "Nick Castellanos",
                   "Randy Arozarena",
                   "Christian Yelich",
                   "Josh Donaldson", 
                   "Hunter Renfroe",
                   "Leody Taveras",
                   "Christopher Morel",
                   "Ty France",
                   "Joey Votto",
                   "Tommy Pham",
                   "Seiya Suzuki")

termi_pitchers <- c("Shane McClanahan",
                    "Julio Urias",
                    "Sandy Alcantara",
                    "Yu Darvish",
                    "Reid Detmers",
                    "Dylan Cease",
                    "Clay Holmes",
                    "Ryan Helsley",
                    "Nick Lodolo",
                    "Andres Munoz",
                    "Josiah Gray",
                    "Triston McKenzie", 
                    "Hunter Greene",
                    "Brett Martin",
                    "Aaron Ashby",
                    "Patrick Sandoval")
```



# **Hitter Reports**

## 15 Days 



### Terminoeckers

```{r}
batters15 <- fg_batter_stats(Sys.Date() - 15, Sys.Date(), qual = 5) 

termis_hitters15 <- batters15 %>%
  filter(Name %in% termi_hitters) %>% 
  select(1:9, 24:29, 10:23, 30:31)

# termis_hitters15 %>% 
#   gt() %>% 
#   data_color(
#     columns = `Barrel%`,
#     colors = scales::col_numeric(
#       palette = c("red", "orange", "green", "blue"),
#       domain = c(0, 35)
#     )
#   ) %>%
#   data_color(
#     columns = `HardHit%`,
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(0, 70)
#     )
#   ) %>%
#   tab_header(
#     title = "Termi Hitters 15 Day Report",
#     subtitle = "Arranged in descending barrel%"
#   )

datatable(termis_hitters15, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```

### MLB

```{r}
datatable(batters15, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```

## 30 Days 




### Terminoeckers 

```{r}
batters30 <- fg_batter_stats(Sys.Date() - 30, Sys.Date(), qual = 5) 

termis_hitters30 <- batters30 %>%
  filter(Name %in% termi_hitters)%>% 
  select(1:9, 24:29, 10:23, 30:31)

datatable(termis_hitters30, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))
```

### MLB

```{r}
datatable(batters30, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```


## 45 Days 



### Terminoeckers 

```{r}
batters45 <- fg_batter_stats(Sys.Date() - 45, Sys.Date(), qual = 5) 

termis_hitters45 <- batters45 %>%
  filter(Name %in% termi_hitters)%>% 
  select(1:9, 24:29, 10:23, 30:31)

datatable(termis_hitters45, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```


### MLB

```{r}
datatable(batters45, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```



------- BREAK -----

# **Pitcher Reports**

## 15 Days 



### Terminoeckers

```{r}
pitchers15 <- fg_pitcher_stats(Sys.Date() - 15, Sys.Date(), qual = 5) 

termis_pitchers15 <- pitchers15 %>%
  filter(Name %in% termi_pitchers)

# termis15 %>% 
#   gt() %>% 
#   data_color(
#     columns = `Barrel%`,
#     colors = scales::col_numeric(
#       palette = c("red", "orange", "green", "blue"),
#       domain = c(0, 35)
#     )
#   ) %>%
#   data_color(
#     columns = `HardHit%`,
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(0, 70)
#     )
#   ) %>%
#   tab_header(
#     title = "Termi Hitters 15 Day Report",
#     subtitle = "Arranged in descending barrel%"
#   )

datatable(termis_pitchers15, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```

### MLB

```{r}
datatable(pitchers15, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```

## 30 Days 




### Terminoeckers 

```{r}
pitchers30 <- fg_pitcher_stats(Sys.Date() - 30, Sys.Date(), qual = 5) 

termis_pitchers30 <- pitchers30 %>%
  filter(Name %in% termi_pitchers)

datatable(termis_pitchers30, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))
```

### MLB

```{r}
datatable(pitchers30, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```


## 45 Days 



### Terminoeckers 

```{r}
pitchers45 <- fg_pitcher_stats(Sys.Date() - 45, Sys.Date(), qual = 5) 

termis_pitchers45 <- pitchers45 %>%
  filter(Name %in% termi_pitchers)

datatable(termis_pitchers45, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```


### MLB

```{r}
datatable(pitchers45, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```






# **Hitter Trends**

Examination of who has improved the most over the past 20 days relative to 20 days prior

### Terminoeckers

Time range 1: **Opening Day** to **`r Sys.Date() - 21`**

Time range 2: **`r Sys.Date()-20`** to **`r Sys.Date()`**

* Note: PA1 is PAs during first time range, PA2 is PAs over last 20 days

```{r}
hitters_trends <- batter_diff("2022-03-01", # To start of the season
            Sys.Date() - 21,
            Sys.Date() - 20,
            Sys.Date(),
            qual1 = 20,
            qual2 = 20) %>%
    mutate_if(is.numeric, ~round(., 3))


termis_hitters_trends <- hitters_trends %>%
  filter(Name %in% termi_hitters)

datatable(termis_hitters_trends, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```


### MLB

```{r}
datatable(hitters_trends, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```

----------------- BREAK--------------

# **Pitcher Trends**

Examination of who has improved the most over the past 20 days relative to 20 days prior

### Terminoeckers

Time range 1: **Opening Day** to **`r Sys.Date() - 21`**

Time range 2: **`r Sys.Date()-20`** to **`r Sys.Date()`**

* Note: PA1 is PAs during first time range, PA2 is PAs over last 20 days

```{r}
pitchers_trends <- pitcher_diff("2022-03-01", # To start of the season
            Sys.Date() - 21,
            Sys.Date() - 20,
            Sys.Date(),
            qual1 = 20,
            qual2 = 5) %>%
    mutate_if(is.numeric, ~round(., 3))


termis_pitchers_trends <- pitchers_trends %>%
  filter(Name %in% termi_pitchers)

datatable(termis_pitchers_trends, options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50)
))

```


### MLB

```{r}
datatable(pitchers_trends, filter = 'top', options = list(
  pageLength = 20,
  legnthMenu = c(5, 10, 20, 50, 100)
))
```





