on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::googlesheets4
            any::baseballr
            any::gt
            any::blastula
            any::glue
            any::keyring

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Load Pre-reqs
        run: Rscript -e 'source("2024 Revamp/1_load_prereqs.R")'

      - name: Batter Daily Stats
        run: Rscript -e 'source("2024 Revamp/batters_daily_stats.R")'

      - name: Pitcher Daily Stats
        run: Rscript -e 'source("2024 Revamp/pitcher_daily_stats.R")'
        
      - name: Email Send
        run: Rscript -e 'source("2024 Revamp/send_email.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add batter_output.rds pitcher_output.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"