name: Email Workflow

on:
  schedule:
    - cron: '0 11 * * *'  # Schedule to run at 6:00 am every morning

jobs:
  load-data-send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::googlesheets4
            any::baseballr
            any::gt
            any::glue
            any::keyring
            any::blastula
            any::gmailr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run exec.R
        run: Rscript -e 'source("2024 Revamp/exec.R")'
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add batter_output.rds pitcher_output.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
